name: asciiborder
description: A flutter package to let users easily add an ASCII art border around any widget.
version: 0.0.1
author: fzztcode
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
